import os

from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

import config.config as cg
from models.configuration_model import Configuration

def str_to_bool(s):
    if s:
        return s.lower() in ("true", "1", "yes", "y")
    return False


def validate_int_env_var(key: str):
    try:
        return int(os.environ.get(key))
    except:
        print(f'environment variable {key} is invalid')

def create_configuration(selection_type_top,relative_weight, equities_per_firm, number_of_firms):
    engine = create_engine(cg.DB_CONNECTION_URL)
    Session = sessionmaker(bind=engine)
    session = Session()

    try:
        config = Configuration(
            equities_per_firm=equities_per_firm,
            number_of_firms=number_of_firms,
            selection_type_top=selection_type_top,
            relative_weight=relative_weight
        )
        session.add(config)
        session.commit()
        session.refresh(config)  # Gets the autogenerated ID
        return config.id
    except Exception as e:
        print(f"error while trying to create configuration {e}")

def remove_file(path):
    if os.path.exists(path):
        try:
            os.remove(path)
            print(f"Deleted file: {path}")
        except Exception as file_err:
            print(f"Error deleting file: {file_err}")

def delete_configuration(config_id):
    engine = create_engine(cg.DB_CONNECTION_URL)
    Session = sessionmaker(bind=engine)
    session = Session()

    try:
        config = session.query(Configuration).filter_by(id=config_id).first()
        if config:
            session.delete(config)
            session.commit()
            print(f"Deleted configuration ID {config_id} and related rows.")
        else:
            print(f"No configuration found with ID {config_id} to delete.")
    except Exception as db_err:
        print(f"Error during DB rollback: {db_err}")


def is_configuration_already_exist(equities_per_firm, number_of_firms, selection_type_top, relative_weight):
    engine = create_engine(cg.DB_CONNECTION_URL)
    Session = sessionmaker(bind=engine)
    session = Session()

    try:
        # Example values to check (replace with actual env values or parameters)
        equities_per_firm = int(os.getenv('EQUITIES_PER_FIRM', 4))  # Replace with real value
        number_of_firms = int(os.getenv('NUMBER_OF_FIRMS', 3))  # Replace with real value
        selection_type_top = str_to_bool(os.getenv('SELECTION_TYPE_TOP', 'True'))  # Replace with real value
        relative_weight = str_to_bool(os.getenv('RELATIVE_WEIGHT', 'False'))  # Replace with real value

        # Query to check if the configuration already exists
        existing_config = session.query(Configuration).filter_by(
            equities_per_firm=equities_per_firm,
            number_of_firms=number_of_firms,
            selection_type_top=selection_type_top,
            relative_weight=relative_weight
        ).first()

        if existing_config:
            print("Configuration already exists:", existing_config.id)
            return True
        else:
            print("Configuration does not exist.")
            return False

    except Exception as e:
        print(f"Error checking configuration: {e}")
        raise e
    finally:
        session.close()
